### ISSUE TITLE
**Program Freezing Alert!**

### ISSUE THREAD

**Issue by LeTanPhuc-01** [thomaschuckle/simple_generators#1]
In your [PrimeGenerator.html](https://github.com/thomaschuckle/simple_generators/blob/main/PrimeGenerator.html) file you stated: 
> This program determine whether an integer is prime or not.

However, I tried to check if the number 415926535897 is prime, and the program freezes at 41592653589 without completing. Could you please help me resolve this issue?

**Comment by thomaschuckle** [comment]
issue fixed, I changed to a better algorithm. Thank you for pointing that out.
